### ISSUE TITLE
Being able to copy emote to clipboard

### ISSUE THREAD

**Issue by AbdShullah** [Mirakurun/emoting-mokou#42]
For now I can only add the emote to tweet. I would like to copy the emote to clipboard, so I can use it somewhere else, for example 
on discord server.

**Comment by Mirakurun** [comment]
I thought about adding a clipboard too.  I'll add this as another update to this app when I have time.

**Comment by Mirakurun** [comment]
Unfortunately, copying images to clipboard is currently not supported on all browsers, especially Firefox.  The Clipboard API also only works with png images.  I would have to convert all emotes from jpeg to png.  See [https://web.dev/async-clipboard/](url)

I will proceed to implement this limited solution, and change it if I can find an alternative workaround.

**Comment by Mirakurun** [comment]
Added feature in commit 989c3dc and 55967cb.
